import type { Metadata } from "next";

import DirectionProvider from "@/components/providers/direction.provider";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        dir="rtl"
        className={"antialiased bg-background min-h-screen font-[YekanBakh]"}
      >
        {/* <Direction */}
        <Header />
        <DirectionProvider dir="rtl">
          <main className="min-h-screen px-8 sm:px-11 py-12 sm:py-16">
            {children}
          </main>
        </DirectionProvider>
        <Footer />
      </body>
    </html>
  );
}
